In [1]:
import math
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
X1 = [[0.5], [1.0], [-1.0], [0.42], [0.24]]
X2 = [[2.4], [4.2], [0.5], [-0.24]]

In [2]:
X = np.concatenate([X1, X2])
lengths = [len(X1), len(X2)]

In [4]:
lengths

[5, 4]

In [3]:
for i in range(0, 256 - 64, 32):
    print(i)

0
32
64
96
128
160


In [4]:
import numpy as np

# The array is loaded into data
data = np.load('/Users/saeedkazemi/Documents/Python/EE6563/Dataset/Ass3/all_obs.npy')

print("The data is:")
print(data)

The data is:
[[[ 13.  25.  30. ... 123. 123. 123.]
  [ 25.  39.   6. ... 122. 122. 122.]
  [ 31.   8.  39. ...  35.  35.  35.]
  [ 43.  46.  13. ...  36.  36.  36.]
  [ 52.  55.  50. ...  37.  37.  37.]
  [ 68.  70.  69. ...  38.  38.  38.]]

 [[ 16.  13.  15. ... 123. 123. 123.]
  [108.   8.  35. ... 122. 122. 122.]
  [120.  29.  23. ...  35.  35.  35.]
  [ 88.  20.  51. ...  36.  36.  36.]
  [ 57.  52.  30. ...  37.  37.  37.]
  [ 95.  42.  64. ...  38.  38.  38.]]

 [[ 15.  12.  36. ... 123. 123. 123.]
  [ 27.  42.  43. ... 122. 122. 122.]
  [ 59.  27.  53. ...  35.  35.  35.]
  [107.  57.  23. ...  36.  36.  36.]
  [ 33.  48.  87. ...  37.  37.  37.]
  [115.  63.  98. ...  38.  38.  38.]]

 ...

 [[ 11.  25.  36. ... 123. 123. 123.]
  [ 20.  17.   8. ... 122. 122. 122.]
  [ 33.   7.  57. ...  35.  35.  35.]
  [ 47.  34.  19. ...  36.  36.  36.]
  [ 56.  44. 112. ...  37.  37.  37.]
  [ 81.  50.  96. ...  38.  38.  38.]]

 [[ 10.  35.   9. ... 123. 123. 123.]
  [ 17.  28.  39. ... 1